package com.design.u035;

import com.google.common.annotations.VisibleForTesting;
import lombok.extern.slf4j.Slf4j;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Random;

/**
 * ID generator  that is userd to generate random IDs.
 * The IDs generated by this class are not absolutely unique,
 * but the probability of duplication is very low.
 *
 * @author yjs
 *
 */
@Slf4j
public class RandomIdGenerator implements LogTraceIdGenerator {

    /**
     * Generate the random ID,The IDs may be duplicated only in extreme situation.
     *
     * @return an random ID
     */

    @Override
    public String generator() {
        String substrOfHostName = null;
        try {
            substrOfHostName = getLastfieldOfHostName();
        } catch (UnknownHostException e) {
            log.error(e.getMessage());
        }
        String randomString = generateRandomAlphameric(8);
        return String.format("%s-%d-%s", substrOfHostName,
                System.currentTimeMillis(), randomString);
    }

    /**
     * 生成合适的随机字符串
     * Generate random string with
     * only contains digits,uppercase letters and lowercase letters.
     *
     * @param length should not be less than 0
     * @return return the random string .Returns empty string if length is 0.
     */
    @VisibleForTesting
    public String generateRandomAlphameric(int length) {
        char[] randomChars = new char[length];
        int count = 0;
        Random random = new Random();
        while (count < length) {
            int maxAscii = 'z';
            int randomAscii = random.nextInt(maxAscii);
            //换种写法去掉多余的if
            boolean isDigit = randomAscii >= '0' && randomAscii <= '9';
            boolean isUppercase = randomAscii >= 'A' && randomAscii <= 'Z';
            boolean isLowercase = randomAscii >= 'a';
            if (isDigit || isUppercase || isLowercase) {
                randomChars[count] = (char) (randomAscii);
                ++count;
            }
        }
        return new String(randomChars);
    }
    /**
     * 从 getLastfieldOfHostName() 函数中，将逻辑比较复杂的那部分代码剥离出来，定义为 getLastSubstrSplittedByDot() 函数。
     * 因为 getLastfieldOfHostName() 函数依赖本地主机名，所以，剥离出主要代码之后这个函数变得非常简单，可以不用测试。
     * 我们重点测试 getLastSubstrSplittedByDot() 函数即可。
     * lastfield主机名
     *
     * @return {@link String}
     * @throws UnknownHostException 未知主机异常
     */
    private String getLastfieldOfHostName() throws UnknownHostException{
        String substrOfHostName;
        try {
            String hostName = InetAddress.getLocalHost().getHostName();
            substrOfHostName = getLastSubstrSplittedByDot(hostName);
        } catch (UnknownHostException e) {
            log.warn("Failed to get the host name.", e);
            throw e;
        }
        return substrOfHostName;
    }


    /**
     * Get the last field of {@hostName} splitted by delemiter '.'
     *
     * @param hostName should not be null
     * @return the last field of {@hostName}.Returns empty string if {@hostName} is empty string
     */
    @VisibleForTesting
    public String getLastSubstrSplittedByDot(String hostName) {
        String[] tokens = hostName.split("\\.");
        //因为substrOfHostName和hostName有不同的语义功能，所以这里不能重用hostName
        String substrOfHostName = hostName;
        if (tokens.length > 0) {
            substrOfHostName = tokens[tokens.length - 1];
        }
        return substrOfHostName;
    }
}
